### ISSUE TITLE
Latest Twig version support

### ISSUE THREAD

**Issue by AdrianZajkowski** [andrew72ru/symfony-db-i18n-bundle#3]
In symfony 5 project, after running 
`composer require creative/symfony-db-i18n-bundle`
there is an error of not supporting latest twig version.

`Using version ^0.3.0 for creative/symfony-db-i18n-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for creative/symfony-db-i18n-bundle ^0.3.0 -> satisfiable by creative/symfony-db-i18n-bundle[v0.3.0].
    - Conclusion: remove twig/twig v3.0.3
    - Conclusion: don't install twig/twig v3.0.3
    - creative/symfony-db-i18n-bundle v0.3.0 requires twig/twig ^2.4 -> satisfiable by twig/twig[v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2, v2.12.3, v2.12.4, v2.12.5, v2.13.0, v2.13.1, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.8.0, v2.8.1, v2.9.0].
    - Can only install one of: twig/twig[v2.10.0, v3.0.3].
    - Can only install one of: twig/twig[v2.11.0, v3.0.3].
    - Can only install one of: twig/twig[v2.11.1, v3.0.3].
    - Can only install one of: twig/twig[v2.11.2, v3.0.3].
    - Can only install one of: twig/twig[v2.11.3, v3.0.3].
    - Can only install one of: twig/twig[v2.12.0, v3.0.3].
    - Can only install one of: twig/twig[v2.12.1, v3.0.3].
    - Can only install one of: twig/twig[v2.12.2, v3.0.3].
    - Can only install one of: twig/twig[v2.12.3, v3.0.3].
    - Can only install one of: twig/twig[v2.12.4, v3.0.3].
    - Can only install one of: twig/twig[v2.12.5, v3.0.3].
    - Can only install one of: twig/twig[v2.13.0, v3.0.3].
    - Can only install one of: twig/twig[v2.13.1, v3.0.3].
    - Can only install one of: twig/twig[v2.4.0, v3.0.3].
    - Can only install one of: twig/twig[v2.4.1, v3.0.3].
    - Can only install one of: twig/twig[v2.4.2, v3.0.3].
    - Can only install one of: twig/twig[v2.4.3, v3.0.3].
    - Can only install one of: twig/twig[v2.4.4, v3.0.3].
    - Can only install one of: twig/twig[v2.4.5, v3.0.3].
    - Can only install one of: twig/twig[v2.4.6, v3.0.3].
    - Can only install one of: twig/twig[v2.4.7, v3.0.3].
    - Can only install one of: twig/twig[v2.4.8, v3.0.3].
    - Can only install one of: twig/twig[v2.5.0, v3.0.3].
    - Can only install one of: twig/twig[v2.6.0, v3.0.3].
    - Can only install one of: twig/twig[v2.6.1, v3.0.3].
    - Can only install one of: twig/twig[v2.6.2, v3.0.3].
    - Can only install one of: twig/twig[v2.7.0, v3.0.3].
    - Can only install one of: twig/twig[v2.7.1, v3.0.3].
    - Can only install one of: twig/twig[v2.7.2, v3.0.3].
    - Can only install one of: twig/twig[v2.7.3, v3.0.3].
    - Can only install one of: twig/twig[v2.7.4, v3.0.3].
    - Can only install one of: twig/twig[v2.8.0, v3.0.3].
    - Can only install one of: twig/twig[v2.8.1, v3.0.3].
    - Can only install one of: twig/twig[v2.9.0, v3.0.3].
    - Installation request for twig/twig (locked at v3.0.3) -> satisfiable by twig/twig[v3.0.3].

Installation failed, reverting ./composer.json to its original content.`

**Comment by andrew72ru** [comment]
This is pretty old project, and if I will have any time, I'll update it, of course

**Comment by andrew72ru** [comment]
@AdrianZajkowski try it now, I've just updated all dependencies and made some refactoring
