### ISSUE TITLE
Symfony 5.2 loader not loaded

### ISSUE THREAD

**Issue by patrickbussmann** [andrew72ru/symfony-db-i18n-bundle#7]
On Symfony 5.2 the dev-master / v3 is not working.

It seems that the loading logic has changed.
Before on https://github.com/andrew72ru/symfony-db-i18n-bundle/blob/d28877b168e3ac10cd69cb6dadf0d6377262016d/src/DependencyInjection/DbI18nExtension.php#L38 there was the cache folder specified and it seems to work.

But now the `cache:clear` created `catalogue.de.sxKOD8d.php.meta` file doesnt contains the cache folder so no translations are load.

When I change it to the following it works.

    $container->setParameter('db_i18n.translation_dir', $container->getParameter('kernel.project_dir') . '/translations');

Maybe there is another way to overwrite the path or injecting the loader directly into the translation system.

**Comment by andrew72ru** [comment]
Thank you, Patrick. I must think about it: it's seems not convenient to developer if some package made files under git (like in translations directory). So, I have to make this files in some place which is ignored by vcs.

**Comment by creiner** [comment]
Any progress on this? :-)

**Comment by andrew72ru** [comment]
@patrickbussmann @creiner I've fixed it :) 

https://github.com/andrew72ru/symfony-db-i18n-bundle/releases/tag/v0.3.1

**Comment by creiner** [comment]
@andrew72ru thanks for the quick reaction! :-)
