### ISSUE TITLE
How do you handle cache?

### ISSUE THREAD

**Issue by Warxcell** [andrew72ru/symfony-db-i18n-bundle#9]
Hello, if I remember correctly - if you use Loader and you change the translation - you need to refresh cache. How do you handle that?

**Comment by andrew72ru** [comment]
By standard procedure. In my case, I made a controller action with `cache:clear` command call.

**Comment by Warxcell** [comment]
But in high traffic website - that will take it down for few seconds (sometimes even it won't be able to restore, because of race condition) - while cache is deleted and somebody hit the website, it will start another cache-regeneration.

**Comment by andrew72ru** [comment]
I suppose, this procedure may have a normal workflow: clear website cache from console command (or re-deploy instance) by PM request to DevOps, for example. Anyway, if we talking about really high-load website, this package may be a bottle-neck, and I will not recommend to use it in highload-case.

This bundle suppose to work in small or middle websites with often changes in translation terms. In process of beta-testing, in test of hypothesis or something like that.

**Comment by Warxcell** [comment]
yeah, but re-deploy makes this whole bundle use-less - the translations to be editable by administrator (not technical user). 

Thank you for your answers.
